services:
  vllm:
    build:
      context: ./docker/
      dockerfile: Dockerfile.vllm
    command: "vllm serve /models/Qwen3-8B-FP8 --host 0.0.0.0"
    # ports:
    #   - "8000:8000"
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
  notebook:
    build:
      context: ./docker
      dockerfile: Dockerfile.notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
