FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    pip3 install --upgrade pip

RUN pip install vllm==0.8.5 --extra-index-url https://download.pytorch.org/whl/cu128 && \
    pip install flashinfer-python -i https://flashinfer.ai/whl/cu126/torch2.6/ && \
    huggingface-cli download --local-dir=/models/Qwen3-8B-FP8 Qwen/Qwen3-8B-FP8
